play-with-docker/Portus/Portus.1/config/routes.rb
Rails.application.routes.draw do
  resources :errors, only: [:show]
  resources :teams, only: [:index, :show, :create, :update] do
    member do
      get "typeahead/:query" => "teams#typeahead", :defaults => { format: "json" }
    end
  end
  get "/teams/typeahead/:query" => "teams#all_with_query", :defaults => { format: "json" }

  resources :team_users, only: [:create, :destroy, :update]
  resources :namespaces, only: [:create, :index, :show, :update] do
    put "change_visibility", on: :member
    resources :webhooks do
      resources :headers, only: [:create, :destroy], controller: :webhook_headers
      resources :deliveries, only: [:update], controller: :webhook_deliveries
      member do
        put "toggle_enabled"
      end
    end
  end
  get "namespaces/typeahead/:query" => "namespaces#typeahead", :defaults => { format: "json" }

  resources :repositories, only: [:index, :show, :destroy] do
    post :toggle_star, on: :member
    resources :comments, only: [:create, :destroy]
  end

  resources :tags, only: [:destroy]

  resources :application_tokens, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions",
                                    passwords:     "passwords" }
  resource :dashboard, only: [:index]
  resources :search, only: [:index]

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
    put "toggle_enabled/:id", to: "auth/registrations#toggle_enabled", as: :toggle_enabled
  end

  namespace :v2, module: "api/v2", defaults: { format: :json } do
    root to: "ping#ping", as: :ping
    resource :token, only: [:show]
    resource :webhooks, only: [] do
      resources :events, only: [:create]
    end
  end

  namespace :admin do
    resources :activities, only: [:index]
    resources :dashboard, only: [:index]
    resources :registries, except: [:show, :destroy]
    resources :namespaces, only: [:index]
    resources :teams, only: [:index]
    resources :users do
      put "toggle_admin", on: :member
    end
  end

  # Error pages.
  %w(401 404 422 500).each do |code|
    get "/#{code}", to: "errors#show", status: code
  end
end

play-with-docker/Portus/Portus.1/app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
    @recent_activities = PublicActivity::Activity
                         .order("created_at DESC")
                         .limit(20)
    @portus_exists = User.where(username: "portus").any?
  end
end

play-with-docker/Portus/Portus.1/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @recent_activities = policy_scope(PublicActivity::Activity)
                         .limit(20)
                         .order("created_at desc")
    @repositories = policy_scope(Repository)

    # The personal namespace could not exist, that happens when portus
    # does not have a registry associated yet (right after the initial setup)
    personal_namespace = current_user.namespace
    @personal_repositories = personal_namespace ? personal_namespace.repositories : []

    @stars = current_user.stars.order("updated_at desc")
  end
end

play-with-docker/Portus/Portus.1/app/views/admin/dashboard/index.html.slim
- unless @portus_exists
  .alert.alert-danger.fade.in.text-left.alert-dismissible
    button.close data-dismiss="alert" type="button"
      span aria-hidden="true" &times;
      span.sr-only Close
    .row
      .alert-icon.pull-left
        i.fa.fa-exclamation-circle.fa-3x
      .pull-left
        p
          | The Portus user does not exist!

.row
  .col-md-3.col-sm-12.registries
    .panel-overview
      .panel-heading
        = link_to 'Registry', admin_registries_path
      .panel-body
        .row
          .col-xs-3.col-md-4
            i.fa.fa-server.registries.fa-2x
          .col-xs-9.col-md-8
            span.fa-3x= Registry.count

  .col-md-3.col-xs-12.users
    .panel-overview
      .panel-heading
        = link_to 'Users', admin_users_path
      .panel-body
        .row
          .col-xs-3.col-md-4
            i.fa.fa-user.users.fa-2x
          .col-xs-9.col-md-8
            span.fa-3x= User.enabled.count

  .col-md-3.col-xs-12.teams
    .panel-overview
      .panel-heading
        = link_to 'Teams', admin_teams_path
      .panel-body
        .row
          .col-xs-3.col-md-4
            i.fa.fa-users.teams.fa-2x
          .col-xs-9.col-md-8
            span.fa-3x= Team.all_non_special.count

  .col-md-3.col-xs-12.namespaces
    .panel-overview
      .panel-heading
        = link_to 'Namespaces', admin_namespaces_path
      .panel-body
        .row
          .col-xs-3.col-md-4
            i.fa.fa-ship.namespaces.fa-2x
          .col-xs-9.col-md-8
            span.fa-3x= Namespace.count

.panel.panel-default
  .panel-heading
    .row
      .col-sm-6
        h5
          | Recent activities
      .col-sm-6.text-right
        = link_to admin_activities_path, class: "btn btn-link btn-xs" do
          i.fa.fa-eye
          ' View all activities

  .panel-body
    - if @recent_activities.empty?
      p No activities in the last 24 hours.
    - else
      ul.activity
        - @recent_activities.each do |activity|
          = render_activity(activity)