play-with-docker/Portus/config/routes.rb
Rails.application.routes.draw do
  resources :errors, only: [:show]
  resources :teams, only: [:index, :show, :create, :update] do
    member do
      get "typeahead/:query" => "teams#typeahead", :defaults => { format: "json" }
    end
  end
  get "/teams/typeahead/:query" => "teams#all_with_query", :defaults => { format: "json" }

  resources :team_users, only: [:create, :destroy, :update]
  resources :namespaces, only: [:create, :index, :show, :update] do
    put "change_visibility", on: :member
    resources :webhooks do
      resources :headers, only: [:create, :destroy], controller: :webhook_headers
      resources :deliveries, only: [:update], controller: :webhook_deliveries
      member do
        put "toggle_enabled"
      end
    end
  end
  get "namespaces/typeahead/:query" => "namespaces#typeahead", :defaults => { format: "json" }

  resources :repositories, only: [:index, :show, :destroy] do
    post :toggle_star, on: :member
    resources :comments, only: [:create, :destroy]
  end

  resources :tags, only: [:destroy]

  resources :application_tokens, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions",
                                    passwords:     "passwords" }
  resource :dashboard, only: [:index]
  resources :search, only: [:index]

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
    put "toggle_enabled/:id", to: "auth/registrations#toggle_enabled", as: :toggle_enabled
  end

  namespace :v2, module: "api/v2", defaults: { format: :json } do
    root to: "ping#ping", as: :ping
    resource :token, only: [:show]
    resource :webhooks, only: [] do
      resources :events, only: [:create]
    end
  end

  namespace :admin do
    resources :activities, only: [:index]
    resources :dashboard, only: [:index]
    resources :registries, except: [:show, :destroy]
    resources :namespaces, only: [:index]
    resources :teams, only: [:index]
    resources :users do
      put "toggle_admin", on: :member
    end
  end

  # Error pages.
  %w(401 404 422 500).each do |code|
    get "/#{code}", to: "errors#show", status: code
  end
end

play-with-docker/Portus/app/models/registry.rb
# == Schema Information
#
# Table name: registries
#
#  id                :integer          not null, primary key
#  name              :string(255)      not null
#  hostname          :string(255)      not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  use_ssl           :boolean
#  external_hostname :string(255)
#
# Indexes
#
#  index_registries_on_hostname  (hostname) UNIQUE
#  index_registries_on_name      (name) UNIQUE
#

# Registry holds data regarding the registries registered in the Portus
# application.
#
# NOTE: currently only one Registry is allowed to exist in the database. This
# might change in the future.
class Registry < ActiveRecord::Base
  has_many :namespaces

  validates :name, presence: true, uniqueness: true
  validates :hostname, presence: true, uniqueness: true
  validates :external_hostname, presence: false
  validates :use_ssl, inclusion: [true, false]

  # On create, make sure that all the needed namespaces are in place.
  after_create :create_namespaces!

  # Today the data model supports many registries
  # however Portus just supports on Registry
  # therefore to avoid confusion, define just one way
  # to ask for the registy
  def self.get
    Registry.first
  end

  # Finds the registry with the given hostname. It first looks for the
  # `hostname` column, and then it fallbacks to `external_hostname`.
  def self.find_by_hostname(hostname)
    registry = Registry.find_by(hostname: hostname)
    if registry.nil?
      Rails.logger.debug("No hostname matching `#{hostname}', testing external_hostname")
      registry = Registry.find_by(external_hostname: hostname)
    end
    registry
  end

  # Returns the global namespace owned by this registry.
  def global_namespace
    Namespace.find_by(registry: self, global: true)
  end

  # Returns a registry client based on this registry that authenticates with
  # the credentials of the "portus" user.
  def client
    Portus::RegistryClient.new(hostname, use_ssl)
  end

  # Find the registry for the given push event.
  def self.find_from_event(event)
    request_hostname = event["request"]["host"]
    registry = Registry.find_by(hostname: request_hostname)
    if registry.nil?
      logger.debug("No hostname matching #{request_hostname}, testing external_hostname")
      registry = Registry.find_by(external_hostname: request_hostname)
    end
    if registry.nil?
      logger.info("Ignoring event coming from unknown registry #{request_hostname}")
    end
    registry
  end

  # Fetch the information regarding a namespace on this registry for the given
  # event. If no namespace was found, then it returns nil. Otherwise, it
  # returns three values:
  #   - A Namespace object.
  #   - A String containing the name of the repository.
  #   - A String containing the name of the tag or nil if the `fetch_tag`
  #     parameter has been set to false.
  def get_namespace_from_event(event, fetch_tag = true)
    repo = event["target"]["repository"]
    if repo.include?("/")
      namespace_name, repo = repo.split("/", 2)
      namespace = namespaces.find_by(name: namespace_name)
    else
      namespace = global_namespace
    end

    if namespace.nil?
      logger.error "Cannot find namespace #{namespace_name} under registry #{hostname}"
      return
    end

    if fetch_tag
      tag_name = get_tag_from_target(namespace, repo, event["target"])
      return if tag_name.nil?
    else
      tag_name = nil
    end

    [namespace, repo, tag_name]
  end

  # Checks whether this registry is reachable. If it is, then an empty string
  # is returned. Otherwise a string will be returned containing the reasoning
  # of the reachability failure.
  def reachable?
    msg = ""

    # rubocop:disable Lint/ShadowedException:
    begin
      r = client.reachable?

      # At this point, !r is only possible if the returned code is 404, which
      # according to the documentation we have to assume that the registry is
      # not implementing the v2 of the API.
      return "Error: registry does not implement v2 of the API." unless r
    rescue Errno::ECONNREFUSED, SocketError
      msg = "Error: connection refused. The given registry is not available!"
    rescue Errno::ETIMEDOUT, Net::OpenTimeout
      msg = "Error: connection timed out. The given registry is not available!"
    rescue Net::HTTPBadResponse
      msg = if use_ssl
        "Error: there's something wrong with your SSL configuration."
      else
        "Error: not using SSL, but the given registry does use SSL."
      end
    rescue OpenSSL::SSL::SSLError => e
      msg = "SSL error while communicating with the registry, check the server " \
        "logs for more details."
      logger.error(e)
    rescue StandardError => e
      # We don't know what went wrong :/
      logger.info "Registry not reachable: #{e.inspect}"
      msg = "Error: something went wrong. Check your configuration."
    end
    # rubocop:enable Lint/ShadowedException:
    msg
  end

  protected

  # Fetch the tag being pushed through the given target object.
  def get_tag_from_target(namespace, repo, target)
    # Since Docker Distribution 2.4 the registry finally sends the tag, so we
    # don't have to perform requests afterwards.
    return target["tag"] unless target["tag"].blank?

    # Tough luck, we should now perform requests to fetch the tag. Note that
    # depending on the Manifest version we have to do one thing or another
    # because they expose different information.
    case target["mediaType"]
    when "application/vnd.docker.distribution.manifest.v1+json",
      "application/vnd.docker.distribution.manifest.v1+prettyjws"
      get_tag_from_manifest(target)
    when "application/vnd.docker.distribution.manifest.v2+json",
      "application/vnd.docker.distribution.manifest.list.v2+json"
      get_tag_from_list(namespace, repo)
    else
      raise "unsupported media type \"#{target["mediaType"]}\""
    end

  rescue StandardError => e
    logger.info("Could not fetch the tag for target #{target}")
    logger.info("Reason: #{e.message}")
    nil
  end

  # Fetch the tag by making the difference of what we've go on the DB, and
  # what's available on the registry. Returns a string with the tag on success,
  # otherwise it returns nil.
  def get_tag_from_list(namespace, repository)
    full_repo_name = namespace.global? ? repository : "#{namespace.name}/#{repository}"
    tags = client.tags(full_repo_name)
    return if tags.nil?

    repo = Repository.find_by(name: repository, namespace: namespace)
    return tags.first if repo.nil?
    resulting = tags - repo.tags.pluck(:name)

    # Note that it might happen that there are multiple tags not yet in sync
    # with Portus' DB. This means that the registry might have been
    # unresponsive for a long time. In this case, it's not such a problem to
    # pick up the first label, and wait for the CatalogJob to update the
    # rest.
    resulting.first
  end

  # Fetch the tag of the image contained in the current event. The Manifest API
  # is used to fetch it, thus the repo name and the digest are needed (and
  # they are contained inside the event's target).
  #
  # Returns the name of the tag if found, nil otherwise.
  def get_tag_from_manifest(target)
    _, _, manifest = client.manifest(target["repository"], target["digest"])
    manifest["tag"]
  end

  # Create the global namespace for this registry and create the personal
  # namespace for all the existing users.
  def create_namespaces!
    count = Registry.count

    # Create the global team/namespace.
    team = Team.create(
      name:   "portus_global_team_#{count}",
      owners: User.where(admin: true),
      hidden: true
    )
    Namespace.create!(
      name:        "portus_global_namespace_#{count}",
      registry:    self,
      visibility:  Namespace.visibilities[:visibility_public],
      global:      true,
      description: "The global namespace for the registry #{Registry.name}.",
      team:        team
    )

    # TODO: change code once we support multiple registries
    User.find_each(&:create_personal_namespace!)
  end
end

play-with-docker/Portus/app/models/registry/auth_scope.rb
# Registry::AuthScope parses the scope string so it can be used afterwards for
# the "registry" type.
class Registry::AuthScope < Portus::AuthScope
  def resource
    reg = Registry.find_by_hostname(@registry.hostname)
    raise ResourceNotFound, "Could not find registry #{@registry.hostname}" if reg.nil?
    reg
  end

  def scopes
    catalog? ? ["all"] : []
  end

  private

  # Returns true if the given scope string corresponds to the /v2/_catalog
  # endpoint.
  def catalog?
    @resource_name == "catalog" && @actions[0] == "*"
  end
end

play-with-docker/Portus/app/controllers/admin/registries_controller.rb
# Allows the creation of exactly one registry. It also allows updating the
# "use_ssl" attribute of a given registry. Doing all this is safe because only
# admin users will be able to reach this controller.
class Admin::RegistriesController < Admin::BaseController
  before_action :registry_created, only: [:new, :create]

  # GET /admin/registries/
  def index
    @registries = Registry.all
  end

  # GET /admin/registries/new
  def new
    @registry = Registry.new
  end

  # POST /admin/registries
  #
  # This method checks whether the given registry is reachable or not. If it
  # is not, then it will redirect back to the :new page asking for
  # confirmation. If the :force parameter is passed, then this check is not
  # done. If this check is passed/skipped, then it will try to create the
  # registry.
  def create
    @registry = Registry.new(create_params)

    # Check the reachability of the registry.
    unless params[:force]
      msg = @registry.reachable?
      unless msg.empty?
        logger.info "\nRegistry not reachable:\n#{@registry.inspect}\n#{msg}\n"
        msg = "#{msg} You can skip this check by clicking on the \"Skip remote checks\" checkbox."
        hsh = { name: @registry.name, hostname: @registry.hostname,
          use_ssl: @registry.use_ssl, external_hostname: @registry.external_hostname }
        redirect_to new_admin_registry_path(hsh), alert: msg
        return
      end
    end

    if @registry.save
      Namespace.update_all(registry_id: @registry.id)
      redirect_to admin_registries_path, notice: "Registry was successfully created."
    else
      redirect_to new_admin_registry_path, alert: @registry.errors.full_messages
    end
  end

  # GET /admin/registries/:id/edit
  #
  # Note that the admin will only be able to edit the hostname if there are no
  # repositories.
  def edit
    @registry            = Registry.find(params[:id])
    @can_change_hostname = !Repository.any?
  end

  # PUT /admin/registries/1
  #
  # Right now this just toggles the value of the "use_ssl" attribute for the
  # given registry. This might change in the future.
  def update
    @registry = Registry.find(params[:id])
    @registry.update_attributes(update_params)
    redirect_to admin_registries_path, notice: "Registry updated successfully!"
  end

  private

  # Raises a routing error if there is already a registry in place.
  # NOTE: (mssola) remove this once we support multiple registries.
  def registry_created
    raise ActionController::RoutingError, "Not found" if Registry.count > 0
  end

  # The required/permitted parameters on the create method.
  def create_params
    params.require(:registry).permit(:name, :hostname, :use_ssl, :external_hostname)
  end

  # The required/permitted parameters on update. The hostname parameter will be
  # allowed depending whether there are repositories already created or not.
  def update_params
    permitted = [:name, :use_ssl, (:hostname unless Repository.any?), :external_hostname].compact
    params.require(:registry).permit(permitted)
  end
end

play-with-docker/Portus/app/views/admin/registries/edit.html.slim
.panel.panel-default
  .panel-heading
    h5
      'Registry:
      strong
        = @registry.name
  .panel-body
    = form_for @registry, url: admin_registry_path(@registry.id), html: {class: 'form-horizontal', role: 'form'} do |f|
      .form-group
        = f.label :name, {class: 'control-label col-md-2'}
        .col-md-7
          = f.text_field(:name, class: 'form-control', required: true, value: @registry.name)
      - if @can_change_hostname
        .form-group
          = f.label :hostname, {class: 'control-label col-md-2'}
          .col-md-7
            = f.text_field(:hostname, class: 'form-control', placeholder: 'registry.test.lan', required: true)
      .form-group
        = f.label :use_ssl, "Use SSL", {class: 'control-label col-md-2', title: 'Set this to enable SSL in the communication between Portus and the Registry', checked: @registry.use_ssl?}
        .col-md-7
          = f.check_box(:use_ssl)
      div.collapse#advanced
        .form-group
          = f.label :external_hostname, "External Registry Name", {class:'control-label col-md-2', title: 'Set this if the name that clients use to communicate with the registry is different than the name that Portus uses to connect'}
          .col-md-7
            - if params[:external_hostname]
              = f.text_field(:external_hostname, class: 'form-control', value: params[:external_hostname], placeholder: '(Optional)', required: false)
            - else
              = f.text_field(:external_hostname, class: 'form-control', placeholder: '(Optional)', required: false)
            span.help-block
              | Portus uses the hostname field to communicate with the registry,
                but this may be on an internal network and inaccessible to the
                client.
                Clients may connect to the registry by a name different to the
                hostname above, for example if it is behind a reverse proxy.
                This field must be set to prevent Portus from ignoring registry
                events originating from this external hostname.
      .form-group
        .col-md-offset-2.col-md-7
          div.btn-toolbar role='toolbar'
            div.btn-group role='group'
              = f.submit('Update', class: 'btn btn-primary')
            div.btn-group role='group'
              span data-toggle='collapse' data-target='#advanced'
                button.btn.btn-primary#advancedButton type='button' data-toggle='button' aria-expanded='false' aria-controls='advanced' Show Advanced
                javascript:
                  $('#advancedButton').click(function() {
                    $(this).text($(this).text() == 'Show Advanced' ? 'Hide Advanced' : 'Show Advanced');
                  });

play-with-docker/Portus/app/views/admin/registries/index.html.slim
- if @registries.empty?
  .panel.panel-default
    .panel-heading
      h5
        | Registries
    .panel-body
      p No registry configured. Please configure one.
      = link_to "Create registry", new_admin_registry_path, {class: 'btn btn-primary', role: 'button'}
- else
  .panel.panel-default
    .panel-heading
      h5
        | Registries
    .panel-body
      .table-responsive
        table.table.table-stripped.table-hover
          col.col-40
          col.col-40
          col.col-10
          col.col-10
          thead
            tr
              th Name
              th Hostname
              th SSL
              th
          tbody
            - @registries.each do |registry|
              tr id="registry_#{registry.id}"
                td= registry.name
                td= registry.hostname
                td
                  i.fa.fa-lg class="fa-toggle-#{registry.use_ssl? ? 'on': 'off'}" title="SSL in the comunication between Portus and this registry is #{registry.use_ssl? ? "enabled" : "disabled"}"
                td
                  a href="#{edit_admin_registry_path(registry.id)}" Edit

  .alert.alert-info
    strong Note well:
    |  right now Portus is designed to handle only a single private Registry.

play-with-docker/Portus/app/views/admin/registries/new.html.slim
.panel.panel-default
  .panel-heading
    h5 New Registry
  .panel-body
    p
      | Portus needs the information from the form below in order to fetch
        information from your registry and keep everything up to date
        (e.g. so tags are added after users push to the registry). Make sure that:

    ul
      li If you check the SSL checkbox, SSL is properly configured on both sides.
      li You include the port to the hostname (e.g. "registry.test.lan:5000").

    p
      | <span>If you have any doubts about this, just check our </span>
      a href="http://port.us.org/documentation.html" target="_blank" documentation
      | . <span>In particular, make sure to check </span>
      a href="http://port.us.org/docs/Configuring-Portus.html" target="_blank" how to configure Portus
      | <span> and </span>
      a href="http://port.us.org/docs/Configuring-the-registry.html" target="_blank" how to configure your private registry
      | .

    br

    = form_for @registry, url: admin_registries_path, html: {class: 'form-horizontal', role: 'form'} do |f|
      .form-group
        = f.label :name, {class: 'control-label col-md-2'}
        .col-md-7
          - if params[:name]
            = f.text_field(:name, class: 'form-control', value: params[:name], required: true, autofocus: true)
          - else
            = f.text_field(:name, class: 'form-control', required: true, autofocus: true)
      .form-group
        = f.label :hostname, {class: 'control-label col-md-2'}
        .col-md-7
          - if params[:hostname]
            = f.text_field(:hostname, class: 'form-control', value: params[:hostname], placeholder: 'registry.test.lan:5000', required: true)
          - else
            = f.text_field(:hostname, class: 'form-control', placeholder: 'registry.test.lan:5000', required: true)
      .form-group
        = f.label :use_ssl, "Use SSL", {class: 'control-label col-md-2', title: 'Set this to enable SSL in the communication between Portus and the Registry'}
        .col-md-7
          - if params[:use_ssl] == "true"
            = f.check_box(:use_ssl, checked: true)
          - else
            = f.check_box(:use_ssl)
      div.collapse#advanced
        .form-group
          = f.label :external_hostname, "External Registry Name", {class:'control-label col-md-2', title: 'Set this if the name that clients use to communicate with the registry is different than the name that Portus uses to connect'}
          .col-md-7
            - if params[:external_hostname]
              = f.text_field(:external_hostname, class: 'form-control', value: params[:external_hostname], placeholder: '(Optional)', required: false)
            - else
              = f.text_field(:external_hostname, class: 'form-control', placeholder: '(Optional)', required: false)
            span.help-block
              | Portus uses the hostname field to communicate with the registry,
                but this may be on an internal network and inaccessible to the
                client.
                Clients may connect to the registry by a name different to the
                hostname above, for example if it is behind a reverse proxy.
                This field must be set to prevent Portus from ignoring registry
                events originating from this external hostname.
      - unless flash[:alert].nil? || flash[:alert].empty?
        .form-group.has-error
          = label_tag :force, "Skip remote checks", {class: 'control-label col-md-2', title: "Force the creation of the registry, even if it's not reachable."}
          .col-md-7
            = check_box_tag(:force)
      .form-group
        .col-md-offset-2.col-md-7
          div.btn-toolbar role='toolbar'
            div.btn-group role='group'
              = f.submit('Create', class: 'btn btn-primary')
            div.btn-group role='group'
              span data-toggle='collapse' data-target='#advanced'
                button.btn.btn-primary#advancedButton type='button' data-toggle='button' aria-expanded='false' aria-controls='advanced' Show Advanced
                javascript:
                  $('#advancedButton').click(function() {
                    $(this).text($(this).text() == 'Show Advanced' ? 'Hide Advanced' : 'Show Advanced');
                  });