play-with-docker/Portus/Portus.1/config/routes.rb
Rails.application.routes.draw do
  resources :errors, only: [:show]
  resources :teams, only: [:index, :show, :create, :update] do
    member do
      get "typeahead/:query" => "teams#typeahead", :defaults => { format: "json" }
    end
  end
  get "/teams/typeahead/:query" => "teams#all_with_query", :defaults => { format: "json" }

  resources :team_users, only: [:create, :destroy, :update]
  resources :namespaces, only: [:create, :index, :show, :update] do
    put "change_visibility", on: :member
    resources :webhooks do
      resources :headers, only: [:create, :destroy], controller: :webhook_headers
      resources :deliveries, only: [:update], controller: :webhook_deliveries
      member do
        put "toggle_enabled"
      end
    end
  end
  get "namespaces/typeahead/:query" => "namespaces#typeahead", :defaults => { format: "json" }

  resources :repositories, only: [:index, :show, :destroy] do
    post :toggle_star, on: :member
    resources :comments, only: [:create, :destroy]
  end

  resources :tags, only: [:destroy]

  resources :application_tokens, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions",
                                    passwords:     "passwords" }
  resource :dashboard, only: [:index]
  resources :search, only: [:index]

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
    put "toggle_enabled/:id", to: "auth/registrations#toggle_enabled", as: :toggle_enabled
  end

  namespace :v2, module: "api/v2", defaults: { format: :json } do
    root to: "ping#ping", as: :ping
    resource :token, only: [:show]
    resource :webhooks, only: [] do
      resources :events, only: [:create]
    end
  end

  namespace :admin do
    resources :activities, only: [:index]
    resources :dashboard, only: [:index]
    resources :registries, except: [:show, :destroy]
    resources :namespaces, only: [:index]
    resources :teams, only: [:index]
    resources :users do
      put "toggle_admin", on: :member
    end
  end

  # Error pages.
  %w(401 404 422 500).each do |code|
    get "/#{code}", to: "errors#show", status: code
  end
end

play-with-docker/Portus/Portus.1/app/models/webhook_header.rb
# == Schema Information
#
# Table name: webhook_headers
#
#  id         :integer          not null, primary key
#  webhook_id :integer
#  name       :string(255)
#  value      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_webhook_headers_on_webhook_id           (webhook_id)
#  index_webhook_headers_on_webhook_id_and_name  (webhook_id,name) UNIQUE
#

# A WebhookHeader is a key value pair, and describes a HTTP header which is
# to be included in a webhook request.
class WebhookHeader < ActiveRecord::Base
  belongs_to :webhook

  validates :name, uniqueness: { scope: :webhook_id }
end

play-with-docker/Portus/Portus.1/app/controllers/webhook_headers_controller.rb
# WebhookHeadersController manages the creation/removal of webhook headers.
class WebhookHeadersController < ApplicationController
  respond_to :html, :js

  before_action :set_namespace
  before_action :set_webhook

  after_action :verify_authorized

  # POST /namespaces/1/webhooks/1/headers
  # POST /namespaces/1/webhooks/1/headers.json
  def create
    @webhook_header = @webhook.headers.build(webhook_header_params)
    authorize @webhook_header

    if @webhook_header.save
      respond_with @namespace, @webhook, @webhook_header
    else
      respond_with @webhook_header.errors, status: :unprocessable_entity
    end
  end

  # DELETE /namespaces/1/webhooks/1/headers/1
  # DELETE /namespaces/1/webhooks/1/headers/1.json
  def destroy
    @webhook_header = @webhook.headers.find(params[:id])

    authorize @webhook_header

    @webhook_header.destroy
    respond_with @namespace, @webhook, @webhook_header
  end

  private

  def set_namespace
    @namespace = Namespace.find(params[:namespace_id])
  end

  def set_webhook
    @webhook = @namespace.webhooks.find(params[:webhook_id])
  end

  def webhook_header_params
    params.require(:webhook_header).permit(:name, :value)
  end
end

play-with-docker/Portus/Portus.1/app/views/webhook_headers/_webhook_header.html.slim
tr id="webhook_header_#{webhook_header.id}"
  td= webhook_header.name
  - if can_manage_namespace?(@namespace)
    td= webhook_header.value
  - else
    td= '*' * webhook_header.value.length
  - if can_manage_namespace?(@namespace)
    td
      a[class="btn btn-default"
        data-placement="left"
        data-toggle="popover"
        data-title="Please confirm"
        data-content='<p>Are you sure you want to remove this webhook header?</p><a class="btn btn-default">No</a> <a class="btn btn-primary" data-method="delete" rel="nofollow" data-remote="true" href="#{namespace_webhook_header_path(namespace, webhook, webhook_header)}">Yes</a>'
        data-html="true"
        tabindex="0"
        role="button"
        ]
        i.fa.fa-trash.fa-lg

play-with-docker/Portus/Portus.1/app/views/webhook_headers/create.js.erb
<% if @webhook_header.errors.any? %>
  $('#alert p').html("<%= escape_javascript(@webhook_header.errors.full_messages.join('<br/>')) %>");
  $('#alert').fadeIn();
<% else %>
  $('#alert p').html("Header '<%= @webhook_header.name %>' was created successfully");
  $('#alert').fadeIn();

  $('#add_webhook_header_form').fadeOut();
  $('#add_webhook_header_btn i').addClass("fa-plus-circle")
  $('#add_webhook_header_btn i').removeClass("fa-minus-circle")

  if ($('#webhook_headers').length > 0) {
    $("<%= escape_javascript(render partial: "webhook_header", locals: {namespace: @namespace, webhook: @webhook, webhook_header: @webhook_header}) %>").appendTo("#webhook_headers");
  }
<% end %>

play-with-docker/Portus/Portus.1/app/views/webhook_headers/destroy.js.erb
<% if @webhook_header.errors.any? %>
  $('#alert p').html("<%= escape_javascript(@webhook_header.errors.full_messages.join('<br/>')) %>");
  $('#alert').fadeIn();
<% else %>
  $("#webhook_header_<%= @webhook_header.id %>").remove();
  $('#alert p').html("Header '<%= @webhook_header.name %>' was removed successfully");
  $('#alert').fadeIn();
<% end %>