play-with-docker/Portus/config/routes.rb
Rails.application.routes.draw do
  resources :errors, only: [:show]
  resources :teams, only: [:index, :show, :create, :update] do
    member do
      get "typeahead/:query" => "teams#typeahead", :defaults => { format: "json" }
    end
  end
  get "/teams/typeahead/:query" => "teams#all_with_query", :defaults => { format: "json" }

  resources :team_users, only: [:create, :destroy, :update]
  resources :namespaces, only: [:create, :index, :show, :update] do
    put "change_visibility", on: :member
    resources :webhooks do
      resources :headers, only: [:create, :destroy], controller: :webhook_headers
      resources :deliveries, only: [:update], controller: :webhook_deliveries
      member do
        put "toggle_enabled"
      end
    end
  end
  get "namespaces/typeahead/:query" => "namespaces#typeahead", :defaults => { format: "json" }

  resources :repositories, only: [:index, :show, :destroy] do
    post :toggle_star, on: :member
    resources :comments, only: [:create, :destroy]
  end

  resources :tags, only: [:destroy]

  resources :application_tokens, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions",
                                    passwords:     "passwords" }
  resource :dashboard, only: [:index]
  resources :search, only: [:index]

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
    put "toggle_enabled/:id", to: "auth/registrations#toggle_enabled", as: :toggle_enabled
  end

  namespace :v2, module: "api/v2", defaults: { format: :json } do
    root to: "ping#ping", as: :ping
    resource :token, only: [:show]
    resource :webhooks, only: [] do
      resources :events, only: [:create]
    end
  end

  namespace :admin do
    resources :activities, only: [:index]
    resources :dashboard, only: [:index]
    resources :registries, except: [:show, :destroy]
    resources :namespaces, only: [:index]
    resources :teams, only: [:index]
    resources :users do
      put "toggle_admin", on: :member
    end
  end

  # Error pages.
  %w(401 404 422 500).each do |code|
    get "/#{code}", to: "errors#show", status: code
  end
end

play-with-docker/Portus/app/models/webhook.rb
# == Schema Information
#
# Table name: webhooks
#
#  id             :integer          not null, primary key
#  namespace_id   :integer
#  url            :string(255)
#  username       :string(255)
#  password       :string(255)
#  request_method :integer
#  content_type   :integer
#  enabled        :boolean          default("0")
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_webhooks_on_namespace_id  (namespace_id)
#

require "base64"
require "typhoeus"
require "securerandom"
require "json"
require "uri"

# A Webhook describes a kind of callback to an endpoint defined by an URL.
# Further parameters are username and password, which are used for basic
# authentication. The parameters request_method and content_type are limitted
# to GET and POST, and application/json and application/x-www-form-urlencoded
# respectively. Webhooks can be enabled or disabled.
# After a webhook has been triggered with the provided parameters, a
# WebhookDelivery object is created.
class Webhook < ActiveRecord::Base
  include PublicActivity::Common

  enum request_method: ["GET", "POST"]
  enum content_type: ["application/json", "application/x-www-form-urlencoded"]

  belongs_to :namespace

  has_many :deliveries, class_name: "WebhookDelivery", dependent: :destroy
  has_many :headers, class_name: "WebhookHeader", dependent: :destroy

  validates :url, presence: true, url: true

  # default to http if no protocol has been specified. If unspecified, the URL
  # validator will fail.
  before_validation do
    unless url.nil? || url.blank?
      self.url = "http://#{url}" unless url.start_with?("http://", "https://")
    end
  end

  before_destroy :update_activities!

  # Handle a push event from the registry. All enabled webhooks of the provided
  # namespace are triggered in parallel.
  def self.handle_push_event(event)
    registry = Registry.find_from_event(event)
    return if registry.nil?

    namespace, = Namespace.get_from_name(event["target"]["repository"], registry)
    return if namespace.nil?

    hydra = Typhoeus::Hydra.hydra

    namespace.webhooks.each do |webhook|
      next unless webhook.enabled

      headers = webhook.process_headers

      args = {
        method:  webhook.request_method,
        headers: headers,
        body:    JSON.generate(event),
        timeout: 60,
        userpwd: webhook.process_auth
      }

      hydra.queue create_request(webhook, args, headers, event)
    end

    hydra.run
  end

  # Handle a delete event from the registry. All enabled webhooks of the provided
  # namespace are triggered in parallel.
  def self.handle_delete_event(event)
    handle_push_event(event)
  end

  # host returns the host part of the URL. This is useful when wanting a pretty
  # representation of a webhook.
  def host
    _, _, host, = URI.split url
    host
  end

  # process_headers returns a hash containing the webhook's headers.
  def process_headers
    { "Content-Type" => content_type }.tap do |result|
      headers.each do |header|
        result[header.name] = header.value
      end
    end
  end

  # process_auth returns a basic auth string if username and password are provided.
  def process_auth
    return if username.empty? || password.empty?
    "#{username}:#{password}"
  end

  # create_request creates and returns a Request object with the provided arguments.
  def self.create_request(webhook, args, headers, event)
    request = Typhoeus::Request.new(webhook.url, args)

    request.on_complete do |response|
      # prevent uuid clash
      loop do
        @uuid = SecureRandom.uuid
        break if WebhookDelivery.find_by(webhook_id: webhook.id, uuid: @uuid).nil?
      end

      WebhookDelivery.create(
        webhook_id:      webhook.id,
        uuid:            @uuid,
        status:          response.response_code,
        request_header:  headers.to_s,
        request_body:    JSON.generate(event),
        response_header: response.response_headers,
        response_body:   response.response_body
      )
    end

    request
  end

  private_class_method :create_request

  private

  # Provide useful parameters for the "timeline" when a webhook has been
  # removed.
  def update_activities!
    _, _, host, = URI.split url
    PublicActivity::Activity.where(trackable: self).update_all(
      parameters: {
        namespace_id:   namespace.id,
        namespace_name: namespace.clean_name,
        webhook_url:    url,
        webhook_host:   host
      }
    )
  end
end

play-with-docker/Portus/app/controllers/webhooks_controller.rb
# WebhooksController manages the creation/removal/update of webhooks.
# Also, it manages their state, i.e. enabled/disabled.
class WebhooksController < ApplicationController
  respond_to :html, :js

  before_action :set_namespace
  before_action :set_webhook, only: [:update, :show, :destroy, :toggle_enabled]

  after_action :verify_authorized, except: [:index]
  after_action :verify_policy_scoped, only: :index

  # GET /namespaces/1/webhooks
  # GET /namespaces/1/webhooks.json
  def index
    authorize @namespace
    @webhooks = policy_scope(Webhook).where(namespace: @namespace).page(params[:page])

    respond_with(@namespace, @webhooks)
  end

  # POST /namespaces/1/webhooks
  # POST /namespaces/1/webhooks.json
  def create
    @webhook = @namespace.webhooks.build(webhook_params)
    authorize @webhook

    if @webhook.save
      @webhook.create_activity :create, owner: current_user
      respond_with @namespace, @webhook
    else
      respond_with @webhook.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /namespaces/1/webhooks/1/1
  # PATCH/PUT /namespaces/1/webhooks/1/1.json
  def update
    authorize @webhook

    if @webhook.update(webhook_params)
      @webhook.create_activity :update, owner: current_user
      respond_with @namespace, @webhook
    else
      respond_with @webhook.errors, status: :unprocessable_entity
    end
  end

  # GET /namespaces/1/webhooks/1
  # GET /namespaces/1/webhooks/1.json
  def show
    authorize @webhook

    @deliveries = @webhook.deliveries.page(params[:page])
    respond_with(@namespace, @webhook)
  end

  # DELETE /namespaces/1/webhooks/1
  # DELETE /namespaces/1/webhooks/1.json
  def destroy
    authorize @webhook

    @webhook.create_activity :destroy, owner: current_user
    @webhook.destroy

    respond_with @namespace, @webhook
  end

  # PATCH/PUT /namespace/1/webhooks/1/toggle_enabled
  def toggle_enabled
    authorize @webhook
    @webhook.update_attribute(:enabled, !@webhook.enabled?)

    if @webhook.enabled?
      @webhook.create_activity :enabled, owner: current_user
    else
      @webhook.create_activity :disabled, owner: current_user
    end

    render template: "webhooks/toggle_enabled", locals: { namespace: @namespace, webhook: @webhook }
  end

  private

  def set_namespace
    @namespace = Namespace.find(params[:namespace_id])
  end

  def set_webhook
    @webhook = @namespace.webhooks.find(params[:id])
  end

  def webhook_params
    params.require(:webhook).permit(:url, :request_method, :content_type, :username, :password)
  end
end

play-with-docker/Portus/app/views/webhooks/_detail.html.slim
.table-responsive
  table.table
    colgroup
        col.col-20
        col.col-80
    tbody
      tr
        th Request method
        td= webhook.request_method
      tr
        th Content type
        td= webhook.content_type
      tr
        th Username
        td
          - if webhook.username.present?
            = webhook.username
          - else
            ' &mdash;
      tr
        th Password
        td
          - if webhook.password.present?
            = '*' * 11
          - else
            ' &mdash;

play-with-docker/Portus/app/views/webhooks/_webhook.html.slim
tr id="webhook_#{webhook.id}"
  td= link_to webhook.url, [namespace, webhook]
  td= webhook.request_method
  td= webhook.content_type
  td
    - if can_manage_namespace?(@namespace)
      a.btn.btn-default[data-remote="true"
        data-method="put"
        rel="nofollow"
        href=url_for(toggle_enabled_namespace_webhook_path(namespace, webhook))
        ]
        - if webhook.enabled?
          i.fa.fa-lg class="fa-toggle-on"
        - else
          i.fa.fa-lg class="fa-toggle-off" title="Click so this webhook gets enabled"
    - else
      - if webhook.enabled?
        i.fa.fa-lg class="fa-toggle-on"
      - else
        i.fa.fa-lg class="fa-toggle-off"
  - if can_manage_namespace?(@namespace)
    td
      a[class="btn btn-default"
        data-placement="left"
        data-toggle="popover"
        data-title="Please confirm"
        data-content='<p>Are you sure you want to remove this webhook?</p><a class="btn btn-default">No</a> <a class="btn btn-primary" data-method="delete" rel="nofollow" data-remote="true" href="#{namespace_webhook_path(namespace, webhook)}">Yes</a>'
        data-html="true"
        tabindex="0"
        role="button"
        ]
        i.fa.fa-trash.fa-lg

play-with-docker/Portus/app/views/webhooks/create.js.erb
<% if @webhook.errors.any? %>
  $('#alert p').html("<%= escape_javascript(@webhook.errors.full_messages.join('<br/>')) %>");
  $('#alert').fadeIn();
<% else %>
  $('#alert p').html("Webhook '<%= @webhook.host %>' has been created successfully");
  $('#alert').fadeIn();

  $('#add_webhook_form').fadeOut();
  $('#add_webhook_btn i').addClass("fa-plus-circle")
  $('#add_webhook_btn i').removeClass("fa-minus-circle")

  if ($('#webhooks').length > 0) {
    $("<%= escape_javascript(render partial: "webhooks/webhook", locals: {namespace: @namespace,webhook: @webhook}) %>").appendTo("#webhooks");
  }
<% end %>

play-with-docker/Portus/app/views/webhooks/destroy.js.erb
<% if @webhook.errors.any? %>
  $('#alert p').html("<%= escape_javascript(@webhook.errors.full_messages.join('<br/>')) %>");
  $('#alert').fadeIn();
<% else %>
  $("#webhook_<%= @webhook.id %>").remove();
  $('#alert p').html("Webhook '<%= @webhook.host %>' has been removed successfully");
  $('#alert').fadeIn();
<% end %>

play-with-docker/Portus/app/views/webhooks/index.html.slim
#add_webhook_form.collapse
  = form_for :webhook, url: namespace_webhooks_path(@namespace), remote: true, html: {id: 'new-webhook-form', class: 'form-horizontal', role: 'form'} do |f|
      .form-group
        = f.label :url, {class: 'control-label col-md-2'}
        .col-md-7
          = f.text_field(:url, class: 'form-control', required: true, placeholder: "URL")
      .form-group
        = f.label :request_method, {class: 'control-label col-md-2'}
        .col-md-7
          = f.select(:request_method, Webhook.request_methods.keys, {}, {class: 'form-control'})
      .form-group
        = f.label :content_type, {class: 'control-label col-md-2'}
        .col-md-7
          = f.select(:content_type, Webhook.content_types.keys, {}, {class: 'form-control'})
      .form-group
        = f.label :username, {class: 'control-label col-md-2'}
        .col-md-7
          = f.text_field(:username, class: 'form-control', required: false, placeholder: "Username for authentication")
      .form-group
        = f.label :password, {class: 'control-label col-md-2'}
        .col-md-7
          = f.text_field(:password, class: 'form-control', required: false, placeholder: "Password for authentication")
      .form-group
        .col-md-offset-2.col-md-7
          = f.submit('Create', class: 'btn btn-primary')

.panel.panel-default
  .panel-heading
    .row
      .col-sm-6
        h5
          small
            a[data-placement="right"
              data-toggle="popover"
              data-container=".panel-heading"
              data-content="<p>A webhook is an HTTP callback which is triggered after an event, e.g. a push event, occurs.</p>"
              data-original-title="What's this?"
              tabindex="0" data-html="true"]
                i.fa.fa-info-circle
          ' Webhooks for
          - if @namespace.name == "portus_global_namespace_1"
            strong
             = link_to " global namespace", @namespace
          - else
            ' namespace
            strong
              = link_to @namespace.name, @namespace
      .col-sm-6.text-right
        - if can_manage_namespace?(@namespace)
          a#add_webhook_btn.btn.btn-xs.btn-link.js-toggle-button[role="button"]
            i.fa.fa-plus-circle
            | Create new webhook
  .panel-body
    .table-responsive
      table.table.table-stripped.table-hover
        col.col-40
        col.col-20
        col.col-20
        - if can_manage_namespace?(@namespace)
          col.col-10
          col.col-10
        -else
          col.col-20
        thead
          tr
            th URL
            th Request method
            th Content type
            th Enabled
            - if can_manage_namespace?(@namespace)
              th Remove
        tbody#webhooks
          - @webhooks.each do |webhook|
            = render partial: 'webhooks/webhook', locals: {namespace: @namespace, webhook: webhook}
  .panel-footer= paginate(@webhooks)

play-with-docker/Portus/app/views/webhooks/retrigger.js.erb
var ns = $('#webhook_delivery_<%= webhook_delivery.id %> td i').first();

<% if webhook_delivery.success? %>
  ns.addClass("fa-check");
  ns.addClass("text-success");
  ns.removeClass("fa-close");
  ns.removeClass("text-danger");
<% else %>
  ns.addClass("fa-close");
  ns.addClass("text-danger");
  ns.removeClass("fa-check");
  ns.removeClass("text-success");
<% end %>

play-with-docker/Portus/app/views/webhooks/show.html.slim
.panel-group
  - if can_manage_namespace?(@namespace)
    .collapse id="update_webhook_#{@webhook.id}"
      = form_for [@namespace, @webhook], remote: true, html: {class: 'form-horizontal', role: 'form'} do |f|
        .panel.panel-default
          .panel-heading
            .input-group
              = f.text_field(:url, class: 'form-control', required: true, placeholder: html_escape(@webhook.url), input_html: { tabindex: 1 })
              .input-group-btn
                button.btn.btn-link.btn-xs.btn-edit-webhook[
                  value="#{@webhook.id}"
                  type="button"
                  class="button_edit_webhook"]
                  i.fa.fa-close
                  | Edit webhook
          .panel-body
            .form-group
              = f.label :request_method, {class: 'control-label col-md-2'}
              .col-md-7
                = f.select(:request_method, Webhook.request_methods.keys, {}, {class: 'form-control'})
            .form-group
              = f.label :content_type, {class: 'control-label col-md-2'}
              .col-md-7
                = f.select(:content_type, Webhook.content_types.keys, {}, {class: 'form-control'})
            .form-group
              = f.label :username, {class: 'control-label col-md-2'}
              .col-md-7
                = f.text_field(:username, class: 'form-control', required: false, placeholder: "Username for authentication")
            .form-group
              = f.label :password, {class: 'control-label col-md-2'}
              .col-md-7
                = f.password_field(:password, class: 'form-control', required: false, placeholder: "Password for authentication")
            .form-group
              .col-md-offset-2.col-md-7
                = f.submit('Save', class: 'btn btn-primary')
            .errors

  .panel.panel-default.webhook_information
    .panel-heading
      h5
        strong
          '#{@webhook.host}
        ' webhook
        small
          a[data-placement="right" data-toggle="popover" data-container=".panel-heading" data-content="<b>Request method</b>: URL endpoint where the HTTP request is sent to.<br/><b>Content type</b>: Description of the webhook request content.<br/><b>Username</b>: Username used for basic HTTP auth.<br/><b>Password</b>: Password used for basic HTTP auth." data-original-title="What's this?" tabindex="0" data-html="true"]
            i.fa.fa-info-circle
        - if can_manage_namespace?(@namespace)
          .pull-right
            button.btn.btn-link.btn-xs.btn-edit-webhook[
              value="#{@webhook.id}"
              class="button_edit_webhook"]
              i.fa.fa-pencil
              | Edit webhook
    .panel-body
      = render partial: "detail", locals: {webhook: @webhook}

- if can_manage_namespace?(@namespace)
  #add_webhook_header_form.collapse
    = form_for :webhook_header, url: namespace_webhook_headers_path(@namespace, @webhook), remote: true, html: {id: 'new-header-form', class: 'form-horizontal', role: 'form'} do |f|
      .form-group
        = f.label :name, {class: 'control-label col-md-2'}
        .col-md-7
          = f.text_field(:name, class: 'form-control', required: true, placeholder: "Name")
      .form-group
        = f.label :value, {class: 'control-label col-md-2'}
        .col-md-7
          = f.text_field(:value, class: 'form-control', required: true, placeholder: "Value")
      .form-group
        .col-md-offset-2.col-md-7
          = f.submit('Create', class: 'btn btn-primary')
      .errors

.panel.panel-default
  .panel-heading
    h5
      ' Headers
      small
        a[data-placement="right" data-toggle="popover" data-container=".panel-heading" data-content="A header is a HTTP header, i.e. is a key-value pair which is included in the HTTP request." data-original-title="What's this?" tabindex="0"]
          i.fa.fa-info-circle
      - if can_manage_namespace?(@namespace)
        .pull-right
          a#add_webhook_header_btn.btn.btn-xs.btn-link.js-toggle-button[role="button"]
            i.fa.fa-plus-circle
            | Create new header
  .panel-body
    .table-responsive
      table.table.table-stripped.table-hover
        colgroup
            col.col-20
            - if can_manage_namespace?(@namespace)
              col.col-70
              col.col-10
            - else
              col.col-80
        thead
          tr
            th Name
            th Value
            - if can_manage_namespace?(@namespace)
              th Remove
        tbody#webhook_headers
          - @webhook.headers.each do |header|
            = render partial: 'webhook_headers/webhook_header', locals: {namespace: @namespace, webhook: @webhook, webhook_header: header}

.panel.panel-default
  .panel-heading
    h5
      ' Deliveries
      small
        a[data-placement="right" data-toggle="popover" data-container=".panel-heading" data-content="A delivery is created once a webhook has been triggered. They are not re-created but updated after retriggering." data-original-title="What's this?" tabindex="0"]
          i.fa.fa-info-circle
  .panel-body
    .table-responsive
      table.table.table-stripped.table-hover
        colgroup
            - if can_manage_namespace?(@namespace)
              col.col-90
              col.col-10
            - else
              col.col-100
        thead
          tr
            th UUID
            - if can_manage_namespace?(@namespace)
              th Retrigger
        tbody#webhook_deliveries
          - @deliveries.each do |delivery|
            tr[id="webhook_delivery_#{delivery.id}"]
              td
                - if delivery.success?
                  i.fa.fa-check.fa-lg.text-success
                - else
                  i.fa.fa-close.fa-lg.text-danger
                = delivery.uuid
              - if can_manage_namespace?(@namespace)
                td
                  - if delivery.webhook.enabled
                    a.btn.btn-default.btn-retrigger-webhook[data-remote="true"
                      data-method="put"
                      rel="nofollow"
                      href=url_for(namespace_webhook_delivery_path(@namespace, @webhook, delivery))
                      ]
                        i.fa.fa-refresh.fa-lg
                  - else
                    a.btn.btn-default.btn-retrigger-webhook[data-placement="left"
                      data-toggle="popover"
                      data-title="Please confirm"
                      data-content='<p>This webhook is disabled. Are you sure you want to retrigger it?</p><a class="btn btn-primary">No</a> <a class="btn btn-default" data-method="put" rel="nofollow" data-remote="true" href="#{url_for(namespace_webhook_delivery_path(@namespace, @webhook, delivery))}">Yes</a>'
                      data-html="true"
                      tabindex="0"
                      role="button"
                      ]
                      i.fa.fa-refresh.fa-lg
  .panel-footer= paginate(@deliveries)

play-with-docker/Portus/app/views/webhooks/toggle_enabled.js.erb
var ns = $('#webhook_<%= webhook.id %> td a i').first();

<% if webhook.enabled? %>
  ns.prop("title", "This webhook is enabled and will be triggered");
  ns.addClass("fa-toggle-on");
  ns.removeClass("fa-toggle-off");
<% else %>
  ns.removeAttr("title");
  ns.addClass("fa-toggle-off");
  ns.removeClass("fa-toggle-on");
<% end %>

$('#alert p').html("Webhook '<%= webhook.url %>' is now <%= webhook.enabled? ? 'enabled' : 'disabled' %>");
$('#alert').fadeIn();

play-with-docker/Portus/app/views/webhooks/update.js.erb
<% if @webhook.errors.any? %>
  $('#alert p').html("<%= escape_javascript(raw(@webhook.errors.full_messages.join('<br/>'))) %>");
  $('#alert').fadeIn();
<% else %>
  $('#update_webhook_<%= @webhook.id %>').toggle()
  $('.webhook_information').toggle();

  var el = $(".button_edit_webhook i.fa");
  el.removeClass('fa-close');
  el.addClass('fa-pencil');

  $('.webhook_information .panel-body').html("<%= escape_javascript(render partial: "detail", locals: {webhook: @webhook}) %>");
  $('#alert p').html("Webhook '<%= @webhook.host %>' has been updated successfully");
  $('#alert').fadeIn();
  $('.webhook_information .panel-heading h5 strong').text("<%= @webhook.host %> ")
<% end %>